### ISSUE TITLE
Build production using Vite React got error "Complex binding patterns require an initialization value"

### ISSUE THREAD

**Issue by phucloc8697** [near/wallet-selector#283]
**Describe the bug**
Using ReactJS and Vite, the project works well when running as develop mode. But when build for production, I got the error 

[commonjs] Complex binding patterns require an initialization value (14:6) in /Users/locnguyen/Documents/demo-near/node_modules/@near-wallet-selector/core/index.esm.js
file: /Users/locnguyen/Documents/demo-near/node_modules/@near-wallet-selector/core/index.esm.js:14:6
12:
13: // https://github.com/zloirock/core-js/issues/86#issuecomment-115759028
14: var global$I =
          ^
15:   // eslint-disable-next-line es/no-global-this -- safe
16:   check(typeof globalThis == 'object' && globalThis) ||

**To Reproduce**
I made a demo repository for reproducing here: [https://github.com/phucloc8697/demo-near](https://github.com/phucloc8697/demo-near)

- After clone the repo, cd to demo-near, then `yarn` and `yarn build`

**Expected behavior**
The build should complete successfully with no error from near-wallet-selector.

**Screenshots**
<img width="837" alt="Screen Shot 2022-05-12 at 10 46 28 AM" src="https://user-images.githubusercontent.com/17939268/167988034-1a62deb1-2697-4469-b0c2-e23c51472907.png">

**Device (please complete the following information):**
 - OS: macOS 12.2.1
 - Yarn 1.22.190
 - Nodded 16.13.1

**Comment by kujtimprenkuSQA** [comment]
Hey @phucloc8697 , thanks for raising this issue!

After some investigation the issue seems to be caused by the `global: {}` property in `vite.config.ts`.

To avoid getting build errors in this case you will need to change it slightly:

```ts
export default defineConfig({
  plugins: [react()],
  define: {
    "global": "window",
    "process.env.NODE_DEBUG": JSON.stringify(""),
  },
})
```

As suggested here: https://github.com/daily-co/daily-js/issues/163#issuecomment-933237039

To demonstrate that build is working I have forked your repo and then published it in gh-pages:

Forked repo: https://github.com/kujtimprenkuSQA/demo-near
Demo: https://kujtimprenkusqa.github.io/demo-near/

If you have any questions please let us know.

**Comment by Yammoe** [comment]
@kujtimprenkuSQA  Thanks, this worked for me.

**Comment by phucloc8697** [comment]
This worked for me. Thanks @kujtimprenkuSQA
