### ISSUE TITLE
Update README for mynearwallet option

### ISSUE THREAD

**Issue by agileurbanite** [near/wallet-selector#308]
@lewis-sqa can we update the README as well?  Is this published as a separate package for my nearwallet like near wallet?

@gutsyphilip as FYI

**Comment by lewis-sqa** [comment]
Hey @agileurbanite,

We've just [published v4.0.0](https://github.com/near/wallet-selector/releases/tag/v4.0.0) after a round of regression testing late last week that includes the new My NEAR Wallet integration [here](https://www.npmjs.com/package/@near-wallet-selector/my-near-wallet).

As a result of the major upgrade, `dev` has been merged into `main` so the README is now aligned by default and references My NEAR Wallet. Please let me know if there's any problems with the new integration. NEAR Wallet is now technically flagged as `deprecated` (as part of #300 ) so that dApps are able to detect if existing users have selected a wallet that's deprecated and build a flow for migrating them to an alternative option
