### ISSUE TITLE
NEAR Wallet is deprecated

### ISSUE THREAD

**Issue by phucloc8697** [near/wallet-selector#329]
**Describe the bug**
"NEAR Wallet is deprecated" when select connect with Near Wallet since v4.1.0. Not sure if this is a bug or intention, but I can use this in v3.1.0

**To Reproduce**
In react example, click Log in button then select Near Wallet.

**Expected behavior**
Redirect to Near Wallet page as usual.

**Comment by lewis-sqa** [comment]
Hi @phucloc8697,

This change was intentional as NEAR are moving away from [NEAR Wallet](https://wallet.near.org/) to [My NEAR Wallet](https://mynearwallet.com/). dApp users that have previously selected NEAR Wallet will be unaffected but this change was made to prevent new selections of wallets that are considered deprecated

**Comment by phucloc8697** [comment]
@lewis-sqa  Got it. But is there any official/unofficial announcement about this intention from NEAR team? Or is there a reasonable explain for why those wallets are being moved away?

**Comment by lewis-sqa** [comment]
@phucloc8697 There's been some internal discussions with NEAR about this move though it was mentioned in this PR: https://github.com/near/wallet-selector/pull/288.

Maybe @MaximusHaximus can help provide more detail?

**Comment by AmmarHumackicSQA** [comment]
Hi @phucloc8697, as Lewis mentioned, the NEAR Wallet at wallet.near.org is moving to a new domain as My Near Wallet (mynearwallet.com). There'll be an awareness campaign and an official announcement soon: https://twitter.com/MyNearWallet/status/1537077521329561600?s=20&t=xP-eVEFNwEp4Y1l9xzLp7A
