### ISSUE TITLE
Ability to access walletUrl on selector.options.network

### ISSUE THREAD

**Issue by hcho112** [near/wallet-selector#338]
**Description**
I'm working on integrating wallet-selector on [ui.multisafe](https://github.com/near/ui.multisafe) repo.

I noticed that wallet-selector will return `selector` object that contains list of `urls` for `network`. (on `selector.options.network`) Since `wallet-selector` will be the entry point for choosing the wallet to be used, it would be ideal to reference all relevant configs/urls from wallet selector instead of maintaining separately on ui.multisafe repo. (So we have single source of truth in terms of network related urls)
 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/6027014/176336221-e45a7da9-5db3-4400-b201-6631385f747d.png">

Everything is good except would be appreciated if I can get access to `walletUrl` from above path. (From `wallet-selector` repo, `resolveWalletUrl` function returns walletUrl but it is not being exposed under `network`. 

**Acceptance Criteria**
Please include `walletUrl` on selector.options.network. (Currently near-wallet and my-near-wallet)

**Comment by lewis-sqa** [comment]
@hcho112 Thanks for opening this issue!

The reason we don't expose `walletUrl` is because (to my understanding) its wallet specific. Only (My) NEAR Wallet requires this config. If you wish to maintain a single source of truth, you can define the `walletUrl` in the dApp side and override the option in `setupNearWallet` and `setupMyNearWallet`

**Comment by lewis-sqa** [comment]
I did a bit more digging on the multisafe repo. It looks like there's 2 use cases(?):

- [Adding balance](https://github.com/near/ui.multisafe/blob/master/src/ui/components/Main/MultiSafe/Sidebar/Actions/Actions.jsx): I'm guessing this is a `Transfer` NEAR action so `signAndSendTransaction` should be used to be wallet agnostic?
- [No account for Ledger public key](https://github.com/near/ui.multisafe/blob/master/src/ui/components/SelectLedgerAccount/SelectLedgerAccount.jsx#L54): This looks like something we should look at handling better in the `modal-ui` package as part of the Ledger flow?

I can see why this configuration is useful outside of the use cases mentioned above though. Maybe it's a naming issue? It feels like the core purpose is to be a fallback wallet (since a browser wallet is "always available")

**Comment by hcho112** [comment]
Hey @lewis-sqa 
Thanks for quick feedback and my apologies for late feedback. 
(I'm new to repository and I'm learning/discovering things as I go on. )

The reason why I requested to expose `walletUrl` was because many of existing codebase on `ui.multisafe` is heavily reply on `near` object:
```
const near = await connect(connectConfig);
```
Where `connectConfig` includes optional field `walletUrl` which can either be `near-wallet` and `my-near-wallet`. So the intention was to use reference the network configuration that is already established on wallet-selector.

However if conditionally exposing `walletUrl` is something that want to be avoided, I'm happy to manage it on dApp side.

**Comment by lewis-sqa** [comment]
Hey @hcho112,

Using the `connect` API from `near-api-js` in its current form is a little problematic in my opinion as it's highly coupled to a single wallet, (My) Near Wallet. This approach conflicts with the idea of Wallet Selector where we try to abstract over the various wallets in the ecosystem so that dApps can essentially say, "I want to sign this transaction using whatever wallet the user has selected". It's for this reason why we decided against exposing `walletUrl` and why we think it's best if this particular use case is handled in the dApp.

I'm going to go ahead and close this issue, but please feel free to reopen if there's more to discuss 🙂
