### ISSUE TITLE
Unable to test WalletConnect on NEAR Guestbook app https://near.github.io/wallet-selector/

### ISSUE THREAD

**Issue by andy-verida** [near/wallet-selector#373]
**Describe the bug** Unable to connect to NEAR Guestbook app [https://near.github.io/wallet-selector/](https://near.github.io/wallet-selector/) with WalletConnect v2

**To Reproduce** Steps to reproduce the behavior:

1.  Go to [https://near.github.io/wallet-selector/](https://near.github.io/wallet-selector/)
2.  Click on Log In button
3.  Choose WalletConnect and scan QR code
4.  Got an error of connection fail as the WalletConnect **Project-ID** is missing in the image below [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/100177554/182520826-f61273f9-40c2-489c-b7a0-d8dd57470133.png)</span>](https://user-images.githubusercontent.com/100177554/182520826-f61273f9-40c2-489c-b7a0-d8dd57470133.png)

**Expected behavior** Expect NEAR Guestbook app and wallet connection to be successful

**Comment by kujtimprenkuSQA** [comment]
Hey, @andy-verida thank you for raising this bug.

We've re-published the guest book example and provided a `projectId` for WalletConnect.

If you have any other questions feel free to ask.

**Comment by andy-verida** [comment]
Hi @kujtimprenkuSQA, thank you for your prompt reply and resolved the issue.

May I ask one more side question. Could you show me how to test the WalletConnect feature(end to end)?
So far I'm using this sample Wallet app https://react-wallet.walletconnect.com/walletconnect, but still unable to get through the very first pairing step with NEAR Guestbook app.

This error showing immediately as soon as  I press connect to the Guestbook app WalletConnect uri.

![Screen Shot 2022-08-03 at 19 52 48](https://user-images.githubusercontent.com/100177554/182612571-e5ff0501-147e-47ca-ab6c-8d5ffb22d244.png)

**Comment by kujtimprenkuSQA** [comment]
Hey, @andy-verida sorry the issue was closed automatically but here's an explanation:

At the moment `WalletConnect` does not officially support `NEAR` but we have been working in the past months to come up with Standards and POC implementations on how WalletConnect and NEAR should work.

To test our current implementation of this guest book example https://near.github.io/wallet-selector/  you will need to fork or clone this version of `web-examples` https://github.com/kujtimprenkuSQA/web-examples and checkout to the `near-support` branch and use this wallet example https://github.com/kujtimprenkuSQA/web-examples/tree/main/wallets/react-wallet-v2.

1. You will need to provide a `projectId` for wallet connect in that example too.
2. Update these dependencies to these versions:     
  `yarn add @walletconnect/sign-client@^2.0.0-beta.102`
  `yarn add@walletconnect/utils@^2.0.0-beta.102`
3. Run the wallet example: `yarn dev`

**Comment by andy-verida** [comment]
@kujtimprenkuSQA NEAR is one of our top focus blockchains at Verida, so we want to try out and implement NEAR features firsthand. 

Thank you for your instruction, I tried to follow it, tweaking it many times, though I still got the **_Failed to decrypt_** error
I recorded a video here: https://www.loom.com/share/acdf4f58a64540a19044cf257c82a7b1

> @andy-verida sorry the issue was closed automatically but here's an explanation:

Should i move this to a new issue? 
Really appreciate you help 🙏

The error:
```
index.es.js?6088:1 Uncaught (in promise) Error: Failed to decrypt
    at En (index.es.js?6088:1:2750)
    at Ge.decode (index.es.js?e35d:1:20452)
    at D.eval (index.es.js?eb21:1:25530)
    at D.emit (index.es.js?e35d:1:2081)
    at Qe.onMessageEvent (index.es.js?e35d:1:34285)
    at async Qe.onProviderPayload (index.es.js?e35d:1:34168)
En @ index.es.js?6088:1
Ge.decode @ index.es.js?e35d:1
eval @ index.es.js?eb21:1
D.emit @ index.es.js?e35d:1
onMessageEvent @ index.es.js?e35d:1
await in onMessageEvent (async)
D.emit @ index.es.js?e35d:1
onMessageEvent @ index.es.js?e35d:1
await in onMessageEvent (async)
onProviderPayload @ index.es.js?e35d:1
await in onProviderPayload (async)
eval @ index.es.js?e35d:1
emit @ events.js?7652:1
onPayload @ provider.js?f853:64
eval @ provider.js?f853:95
emit @ events.js?7652:1
onPayload @ ws.js?dc4f:108
socket.onmessage @ ws.js?dc4f:89
next-dev.js?3515:25 {context: 'client'} {context: 'client/expirer'} 'No matching key. expirer: topic:0f06a7dd14b76b9a564b2aaa008095e2277c00dff944d32923c4d309edd5c241'
```

**Comment by kujtimprenkuSQA** [comment]
Hey, @andy-verida I might have pointed you to an old branch sorry.

Just pushed a new branch: **SQC-170/bridge-wallet-poc-update-deps**
1. Pull the changes and switch to this branch: https://github.com/kujtimprenkuSQA/web-examples/tree/SQC-170/bridge-wallet-poc-update-deps
2. run `yarn install`
3. Create a .env.local file under **wallets/react-wallet-v2/** and update it with the following content:
`NEXT_PUBLIC_PROJECT_ID=your-wallet-connect-projectID`
`NEXT_PUBLIC_RELAY_URL=wss://relay.walletconnect.com`

You can get your WalletConnect project id on their website: https://cloud.walletconnect.com/sign-in.

**Please note**: In the branch shared at step 1 you might see some errors in the example wallet but signIn, signOut, and other functionality works fine, this is because I have not aligned everything this might be helpful if you wish to fix them too:
https://github.com/WalletConnect/web-examples/pull/37

In the future this is the branch we will maintain: **SQC-170/bridge-wallet-poc** but right now we have some other priorities sorry for the inconvenience.

**Comment by andy-verida** [comment]
Hey @kujtimprenkuSQA, you're super fast! thanks again, I will try with the branch **_SQC-170/bridge-wallet-poc-update-deps_**.

> In the future this is the branch we will maintain: SQC-170/bridge-wallet-poc but right now we have some other priorities sorry for the inconvenience.

No worries, I know this is an ongoing development and still good enough for us to quickly develop the POC for our single sign-on to dApps feature.
