### ISSUE TITLE
Class Action is missing in schema: actions.actions

### ISSUE THREAD

**Issue by Calcifer1001** [near/wallet-selector#389]
**Describe the bug**
I'm doing a sign and send transaction call, getting the error from the title. I've seen in https://github.com/near/wallet-selector/pull/94 that this has already been reviewed. Were you able to solve it?

**To Reproduce**
Logging with MyNearWallet and calling a signAndSendTransaction method

**Expected behavior**
I expected to be redirected to MyNearWallet

**Screenshots**

**Device (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 104.0.5112.81

**Additional context**

**Comment by kujtimprenkuSQA** [comment]
Hey, @Calcifer1001 thank you for raising this issue.

You may see this error because the version of `near-api-js` in your dApp and the version of `near-api-js` in `wallet-selector` do not match.

We have addressed this on this PR, and will be part of the next release: https://github.com/near/wallet-selector/pull/353

In the meantime to avoid this seeing this error install the exact version of near-api-js we have in wallet-selector:

"near-api-js": "0.44.2"

**Comment by Calcifer1001** [comment]
Thank you. That solved my issue!
