### ISSUE TITLE
Error: Class Action is missing in schema: actions. actions

### ISSUE THREAD

**Issue by paouvrard** [near/wallet-selector#401]
**Describe the bug**
signAndSendTransaction caused `Error: Class Action is missing in schema: actions. actions` with v5.0.3
Example call: https://github.com/aurora-is-near/rainbow-bridge-client/blob/0e75c093fb44e50931519f81307dd879b7f002d3/packages/aurora-nep141/src/natural-nep141/sendToAurora/index.ts#L443

**To Reproduce**
Install dependencies as:
```
    "@near-wallet-selector/core": "5.0.3",
    "@near-wallet-selector/modal-ui": "5.0.3",
    "@near-wallet-selector/my-near-wallet": "5.0.3",
    "@near-wallet-selector/near-wallet": "5.0.3",
    "@near-wallet-selector/sender": "5.0.3",
```

I was able to get around the issue by adding  `"@near-wallet-selector/wallet-utils": "5.0.2"` to the dependencies. Adding `"@near-wallet-selector/wallet-utils": "5.0.3"` instead also caused the error.

next.js 12.1.0, react 17.0.2

![photo_2022-08-16 17 20 23](https://user-images.githubusercontent.com/29397451/184832624-8030c99d-013e-4f78-83dc-f776a6d66faa.jpeg)

**Comment by kujtimprenkuSQA** [comment]
Hey, @paouvrard  thank you for raising this issue.

You may see this error because the version of `near-api-js` in your dApp and the version of `near-api-js` in wallet-selector do not match.

We have addressed this on this PR, and will be part of the next release: https://github.com/near/wallet-selector/pull/353

In the meantime to avoid this seeing this error install the exact version of near-api-js we have in wallet-selector:

"near-api-js": "0.44.2"

**Comment by paouvrard** [comment]
Thank you @kujtimprenkuSQA that also worked !
