### ISSUE TITLE
"modal" class is incompatible with Bootstrap

### ISSUE THREAD

**Issue by gagdiez** [near/wallet-selector#415]
If the project includes Bootstrap 5.0 or 5.2 the modal UI does not appear. This is easily solvable by adding a `display: inline;` to the css rule `.nws-modal-wrapper .modal`

**To Reproduce** Add Bootstrap to the project by including:

**Comment by gagdiez** [comment]
Fixed in #416

**Comment by kujtimprenkuSQA** [comment]
Hey, @gagdiez thank you for raising this issue.

I think the issue is with all the classes we have that conflict with bootstrap classes like `.modal`,  `.modal-header`  and `.modal-body` 

Your PR #416 fixes the issue of showing the modal but it looks like we will need to add a prefix to these classes.

**Comment by gagdiez** [comment]
In my tests at least the only problem was the visibility of the modal. Once visible the shape/proportions and behaviour was correct.

Maybe for future bootstrap releases it would be safer to rename all classes, but for now, just by adding the `visibility` rule the error is solved.
