### ISSUE TITLE
`Action` type not compatible with the `Action` type returned by `near-api-js`

### ISSUE THREAD

**Issue by jessupjn** [near/wallet-selector#483]
**Description**
Many SDK's use [`near-api-js`](https://github.com/near/near-api-js) to build actions. The problem is that the `Action` type in `near-api-js` is not compatible with the `Action` type required by `wallet-selector`'s `signAndSendTransaction`.

**Acceptance Criteria**
There should be some method to support this use-case. This might be:
- A function to map the `Action` implementation in `near-api-js` to `wallet-selector`'s `Action`
- A core `Action` type should be used by all official Near repositories.

**Comment by kujtimprenkuSQA** [comment]
Hey, @jessupjn thank you for raising this issue.

It's true that at first glance you will notice that the structure of an `Action` in Wallet Selector is a bit different from what you would normally send using only `near-api-js`, the idea was to simplify the types into something that's easy to use and somehow more "human readable".

If a wallet does not accept/support actions in the structure that are in Wallet Selector then we already have the functionality to convert the `Wallet Selector` Action into a compatible `near-api-js` Action.

This can be found in the `@near-wallet-selector/wallet-utils` package:
https://github.com/near/wallet-selector/blob/main/packages/wallet-utils/src/lib/create-action.ts#L18

Since we already have a [function](https://github.com/near/wallet-selector/blob/main/packages/wallet-utils/src/lib/create-action.ts#L18) that would convert a `Wallet Selector` Action into a `near-api-js` Action, adding an extra helper function that does the opposite is doing too much work just to pass an action in my opinion.

The docs for all NEAR Actions can be found in the link below: 
https://github.com/near/wallet-selector/blob/main/packages/core/docs/api/transactions.md

**Comment by AmmarHumackicSQA** [comment]
I will close this issue for now but feel free to reopen it if you have any additional questions. Thanks @jessupjn
