### ISSUE TITLE
React 18 Bugs

### ISSUE THREAD

**Issue by thalasith** [near/wallet-selector#549]
When I migrated the react example into my  project, a typescript error complaining about the children appeared in the "WalletSelectorContext".  Screenshot below

<img width="1091" alt="Screen Shot 2022-11-07 at 7 24 35 PM" src="https://user-images.githubusercontent.com/19679412/200585441-67e05684-3fd1-4bd7-9667-d7bc90cf0b93.png">

It appears to be an issue with React 18 since "React 18 removed children from the FC type." per Stackoverflow.

I made a change in it to include a Props type per the below and the error disappeared:

type Props = {
  children?: React.ReactNode;
};
export const WalletSelectorContextProvider: React.FC = ({
  children,
}: Props)

But there is another issue under "index.tsx" where the WalletSelectorContext has an error per the below. It appears to be related (i.e. something changed in React 18) but I can't resolve the issue yet. Let me know if there's anything else you need to help replicate the error.
<img width="903" alt="Screen Shot 2022-11-08 at 6 04 42 AM" src="https://user-images.githubusercontent.com/19679412/200585798-14e9427c-9a5a-4f83-9375-12d84bf90321.png">

**Comment by kujtimprenkuSQA** [comment]
Hey, @thalasith thank you for raising this issue.

The error/warning shows because in **React 18** with Typescript by default in `tsconfig,json` in `compilerOptions` you have the value of `strict` set to `true`.

To fix this you can either set the value of `strict` to `false` or you can provide the proper type:

```ts
export const WalletSelectorContextProvider: React.FC<{ children: ReactNode; }> = ({ children }) => {
  // the rest of the code...
}
```

From what I could read on different websites, the `Ract.FC` has not been removed in **React 18**, it seems like it was removed from the TypeScript template of **create-react-app** to avoid inciting to use it. 
This means it can still be used in React 18 but CRA does not create components/contexts by default and set the type of them to `React.FC`.

**Comment by thalasith** [comment]
Yup! Thanks - I stick a "@ts-ignore" to avoid the issue. Flagged it in case other iterations of React causes further issues

**Comment by AmmarHumackicSQA** [comment]
Thanks for raising this issue @thalasith. I will close it, for now, and feel free to reopen it if you have any other issues or questions.
