### ISSUE TITLE
Requesting full access key from the wallet selector

### ISSUE THREAD

**Issue by gwhartson** [near/wallet-selector#553]
Hi,

I am having an issue with requesting full access key from the near wallet selector.

In the code below, I am using the old near-api-js and I create an access key, assign in to keystore, redirect to the login screen passing the access key as a url param, this requests full access. 

```
  const currentUrl = new URL(window.location.origin + window.location.pathname);
  const LOGIN_WALLET_URL_SUFFIX = "/login/";
  const newUrl = new URL(wallet._walletBaseUrl + LOGIN_WALLET_URL_SUFFIX);

  const accessKey = KeyPair.fromRandom("ed25519");
  newUrl.searchParams.set("public_key", accessKey.publicKey.toString());

  await keyStore.setKey(networkId, account.accountId, accessKey);

  window.location.assign(newUrl.toString());
```

I want to know how to do the same with the wallet selector?

Is there a _walletBaseUrl attribute available? 

Do all of the new wallets implement this standard of passing a public key url param and setting it to a full access key?

Thanks

**Comment by amirsaran3** [comment]
@gwhartson I'm not completely sure what you are trying to accomplish here. This looks like a bad practice to me.

You will not be able to use this method with the wallet selector because not all wallets work like the Near Wallet. They are not browser type wallets. For this reason this would not work.

You should convert to only storing limited access keys on your dApp.

I will close this issue for now. If you want to continue this discussion you can reopen it.
