### ISSUE TITLE
Ability to track first login on dApp

### ISSUE THREAD

**Issue by ahnafalfariza** [near/wallet-selector#596]
**Is your feature request related to a problem? Please describe.**
Currently, we use the subscription like in the [example](https://github.com/near/wallet-selector/blob/main/examples/react/contexts/WalletSelectorContext.tsx#L111) to get the account. However, when user refreshes the page, it is no difference between the user's first log-in and who has logged in before. 

on `near-api-js`, we can circumvent this by adding wallet callback URL by custom query string. 

Is there a way to track on dApp if this account is first logged?

**Describe the solution you'd like**
Perhaps adding `onSuccess` params to modal-ui

**Comment by kujtimprenkuSQA** [comment]
Hey, @ahnafalfariza thank you for raising this issue.

I don't fully understand your question, in `near-api-js` there's no callbackUrl when you sign in although there is a `successUrl` and a `failureUrl` this is also supported in wallet-selector if you use browser wallets because they are the only ones that require a redirect.

You can provide these 2 options on the setup of the wallet they will be passed to`signIn` method internally:

```ts
const selector = await setupWalletSelector({
  network: "testnet",
  modules: [
    setupNearWallet({
      successUrl: "https://<Your Success URL>",
      failureUrl: "https://<Your Failure URL>",
    }),
  ],
});
```

Here are the docs with the list of params the `signIn` method expects in different wallets:
https://github.com/near/wallet-selector/blob/main/packages/core/docs/api/wallet.md#signinparams

Here are the docs about the different events emitted by the wallet selector:
https://github.com/near/wallet-selector/blob/main/packages/core/docs/api/selector.md#onevent-callback

If I have misunderstood your question please let me know.

**Comment by ahnafalfariza** [comment]
Thanks for the quick reply! pardon me, yes, I mean `successUrl` and `failureUrl`. 

Turn's out I still use the old version 😅, that's why I couldn't find "signedIn" event nor successUrl params

**Comment by ahnafalfariza** [comment]
Anyway @kujtimprenkuSQA just to make sure. I tried login using near-wallet, however events "signedIn" is not called. Is this expected?

https://codesandbox.io/s/elastic-borg-k04ln5?file=/src/App.js

**Comment by kujtimprenkuSQA** [comment]
That is happening because the flow gets broken when you get redirected redirect, if you use other wallets which don't require redirecting (sender, math, meteor wallet etc..) the event should be emitted.

**Comment by ahnafalfariza** [comment]
ok got it
