### ISSUE TITLE
Configuration for how transactions are signed (Function Call Access Key vs Wallet integration)

### ISSUE THREAD

**Issue by toteto** [near/wallet-selector#669]
**Is your feature request related to a problem? Please describe.**

The usecase of my DApp there is only single interaction with the Near chain. For the purpose of this, it makes more sense to make the singing of the transaction by using the wallet Full Access key instead of creating Function Call access key dedicated to the DApp and the smart contract.

The current implementation of most wallet-selector modules don't have a stable way of achieving single sign transaction without it creating function call access key.

**Describe the solution you'd like**

Easiest place to put this would be maybe in the `modal-ui` right next to the `contractId`. Or maybe it can be implicitly deducted when the `contractId` is se to `undefined`/`null`.

**Describe alternatives you've considered**

- Providing empty string `''` in the `contractId` field
- Providing empty array for `methods`

Both of these behave differently on different wallet integrations. Not reliable.

**Acceptance criteria**

- The DApp has the ability to define desired way of interacting with Near
  - Prefer Function Call access key
  - Prefer individual wallet integrations

**Comment by DamirSQA** [comment]
Hi @toteto , thanks for raising an issue, we're taking a look on it.

**Comment by DamirSQA** [comment]
Hi @toteto , the fix is applied, and it will be included with the next release.

**Comment by toteto** [comment]
Thanks @DamirSQA , will check it out when I get the release!

**Comment by DamirSQA** [comment]
Yes, the fix is included the release.

**Comment by toteto** [comment]
@DamirSQA can you please let me know how this issue is related to the fix you provided via https://github.com/near/wallet-selector/pull/698? 

Also reading through the release notes it seems that this issue is not resolved.

**Comment by Damirhub** [comment]
Hey, @toteto this issue was closed by the fact that now you can `signIn` to some wallets by setting the `contractId` to an empty string. 
Just to give you more context on the topic of `signIn`: At the moment there is no correct way to signIn with wallet selector without creating a FunctionCall Access Key, based on the Standard [here](https://github.com/near/NEPs/blob/master/specs/Standards/Wallets/InjectedWallets.md#signin) sign-in means creating a FAK. Some wallets allow you sign-in by passing the `contractId` as an empty string but that should not be the case because in those wallets `signIn` is doing two different things. The plan is for wallet selector to add a new way to signIn without adding a FunctionCall Access Key by following the `signMessage` NEP which is still in progress, in wallet selector this would ideally be done by using the `verifyOwner` function which we will need to update once everything is finalized regarding the mentioned NEP. If we have misunderstood something about this issue please let us know.

**Comment by toteto** [comment]
Thanks for the explanation. Hope the official support for signIn without FAK woudn't take so long. Do you have a issue that is tracking this, would be helpful maybe to link it here so people can navigate to it and track it.

**Comment by Damirhub** [comment]
You're welcome, you can have a look on [this](https://github.com/near/NEPs/pull/413) PR.
