### ISSUE TITLE
Error happens while connecting XDEFI wallet with new created account

### ISSUE THREAD

**Issue by max-mainnet** [near/wallet-selector#692]
**Describe the bug**
There is an error when connecting XDEFI wallet on https://near.github.io/wallet-selector/ with new created account. 

**To Reproduce**
1. Go to https://near.github.io/wallet-selector/ 
2. Create a new account on XDEFI wallet
3. Sign in by this new created account

**Expected behavior**
Need a tip to show that need storage deposit to this account, and reject sign in, then guide user to deposit. 
For this newly created account with storage staked, any information of this account can not be found in the NEAR chain, and can not do function calls or send transactions. 

**Screenshots**
![IMAGE 2023-02-08 18:19:28](https://user-images.githubusercontent.com/50706666/217502081-1020d818-1056-415d-af43-82083e58296a.jpg)

**Device (please complete the following information):**
 - OS: Mac OS
 - Browser chrome 

**Additional context**

**Comment by kujtimprenkuSQA** [comment]
This is not handled by the wallet selector during `signIn`.

This is an error thrown on the dApp side in the **Guest Book Example** when we try to [view the account](https://github.com/near/wallet-selector/blob/main/examples/react/components/Content.tsx#L38) and this account apparently has no `amount` of NEAR on it.

Technically this should not happen because when we call the `signIn` in a wallet means creating a FunctionCall access key for that account and then returning it to the wallet selector, but the issue here is that XDEFI is not creating a FAK when we `signIn` so they don't check or throw when there's no balance for the chosen account.

The best we can do on our side is maybe catch the error on the `example` dApp and display an `alert` with the message: 
_**Account ID: f3174037f0a1daa1c2eb3ecdf2550ee429927d6cce04aaa6b24e5b14bf9ec609 has not been founded. Please send some NEAR into this account.**_

**Comment by max-mainnet** [comment]
Thanks, an alert should be the way to make the error clear.
