### ISSUE TITLE
Broken redirect link to wallet.near.org

### ISSUE THREAD

**Issue by roshaans** [near/wallet-selector#732]
**Describe the bug**
When trying to save a large widget on Near.social, wallet selector redirects to an inaccessible wallet.near.org page. Such as this example [here](https://gist.github.com/roshaans/316fce593aca3976e5c3a63ca33b4e18). I am trying to save the following [widget code](https://gist.github.com/roshaans/e0dfcfbe95c48a9e27e123ae9b5199a0). 

There may be a max transaction bytes that are able to be sent via the URL path parameters and I seem to be hitting its limits as publishing smaller widgets do not seem to be a problem.

Is this a problem wallet.near.org should resolve or the wallet selector?

**Screenshots**
![image](https://user-images.githubusercontent.com/25015977/225690007-8bbfadba-d1cf-41c6-b129-ca4bc44e0512.png)

**Additional context**
I have saved often larger widgets and have not stumbled across this before.

**Comment by kujtimprenkuSQA** [comment]
Hi @roshaans, thank you for raising this issue.

Wallet Selector makes use of `near-api-js` to interact with **Near Wallet** so internally we use the [account.requestSignTransaction](https://github.com/near/near-api-js/blob/master/packages/near-api-js/src/wallet-account.ts#L300) of NAJ and that's where the logic for handling the transaction lives.

>Is this a problem wallet.near.org should resolve or the wallet selector?

This is not an issue caused by wallet-selector, the error is HTTP 414 which means the URI is too long, it's longer than what the wallet's server is willing to/can interpret:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414

If you use other wallet types like "Injected Wallets" you won't encounter this kind of problem.

If using Near Wallet is a must then the best place is to raise an issue on the wallet's repo where someone more knowledgeable about the wallet can answer your question:
https://github.com/near/near-wallet

**Comment by DamirSQA** [comment]
Hi, I'll just add an idea for a workaround.
As the URL do not exceed limitation by a large margin, maybe is possible to optimize the code to take less size, or to be split on two widgets.
