### ISSUE TITLE
Cannot change contract to log in with

### ISSUE THREAD

**Issue by wackazong** [near/wallet-selector#737]
**Describe the bug**
After an attempt to log in with a specific contract, a further attempt to log in with another contract does not take the change of contract into account.

**To Reproduce**
See test case here https://github.com/wackazong/guest-book-js
Just `run npm install && npm start`. Two login buttons will be displayed which are hardcoded to two different contract addresses. Clicking on either of them locks the contract that is used in the wallet selector, the modal will always show with the same contract address.

**Expected behavior**
Each login attempt should honor the contractId passed to `setupModal`.

**Screenshots**
https://youtu.be/4vZVptNwg50

**Device (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version latest

**Additional context**
None

**Comment by HarisSQA** [comment]
The error is showing because these accounts do not exist in the network with which you are trying to sign-in in.

From what we see in the video you call `setupModal(params)` every time you click a button, it is recommended to call this function only once because this `setupModal` works in a similar pattern as a `singleton`.

Once you call the `setupModal` the `modal`  instance will be created and no matter how many times you call the `setupModal` in the future it will always return the first instance that was created.

With the correct `contractId` you will be redirected to the wallet and after successful signing in you get then redirected to the dApp. (Guestbook)

Eg:
```ts
import { setupWalletSelector } from "@near-wallet-selector/core";
import { setupNearWallet } from "@near-wallet-selector/near-wallet";

const selector = await setupWalletSelector({
  network: "mainnet",
  modules: [setupNearWallet()],
});

const modal1 = setupModal(selector, {  contractId: "numberone.near" });
const modal2 = setupModal(selector, {  contractId: "numbertwo.near" });

console.log(modal1 === modal2); // true
```

**Comment by wackazong** [comment]
Ok, if I understand you correctly, if `setupModal` should be called only once, logging into different contracts in a dApp is not a supported scenario?

**Comment by HarisSQA** [comment]
You, can still call `setupModal` on your dApp every time you click the **Login button** if that’s easier for you.

To change the contract you will need to handle it on the dApp side, you need to sign out from the current logged-in, change `contractId` and reload the page, next time the `setupModal` is called it will be set up with the new contractId.

At the moment you can sign in only with one `contractId` at a time, sign-in with multiple contacts is not supported yet.
