### ISSUE TITLE
[Defect] Already passed to createRoot()

### ISSUE THREAD

**Issue by ALuhning** [near/wallet-selector#980]
**Describe the bug**

Getting following error in the console:

<img width="253" alt="image" src="https://github.com/near/wallet-selector/assets/50085912/7e922df1-67fd-48b4-b681-cc87393b499b">

 Seems to be coming from this code in our vmInitializer.js file of a BOS gateway template:

`useEffect(() => {
    if (!near) {
      return;
    }
    near.selector.then((selector: any) => {
      setWalletModal(setupModal(selector, { contractId: near.config.contractName }));
    });
  }, [near]);`

See there is a similar [closed issue](https://github.com/near/wallet-selector/issues/605).

Is there a way to get rid of this error?

**Comment by kujtimprenkuSQA** [comment]
Hi, @ALuhning thank you for raising this issue.

You're right the "warning/error" is coming from our `setupModal` function, apparently what's happening is that `createRoot` gets triggered every time `setupModal` is invoked in a dApp, this can happen because of some re-rendering of the component/context where `setupModal` is placed or on hot-reload during development.

> Is there a way to get rid of this error?

Yes, it's possible to get rid of it.

From the next release, you can expect not to see this warning.

**Comment by kujtimprenkuSQA** [comment]
Closing this issue because the fix was included in today's release `v8.7.1`.
